// Auto-generated by scripts/gen_firmware_hex.py - do not edit.
localparam FW_WORDS = 15;
function [31:0] fw_rom_word;
  input [31:0] idx;
  begin
    case (idx)
      0: fw_rom_word = 32'hc01fafff;
      1: fw_rom_word = 32'hc000b010;
      2: fw_rom_word = 32'ha2b6a800;
      3: fw_rom_word = 32'hc2a2b800;
      4: fw_rom_word = 32'hc0000848;
      5: fw_rom_word = 32'h0ae10800;
      6: fw_rom_word = 32'hc0000869;
      7: fw_rom_word = 32'h0ae10800;
      8: fw_rom_word = 32'hc0000821;
      9: fw_rom_word = 32'h0ae10800;
      10: fw_rom_word = 32'hc000080d;
      11: fw_rom_word = 32'h0ae10800;
      12: fw_rom_word = 32'hc000080a;
      13: fw_rom_word = 32'h0ae10800;
      14: fw_rom_word = 32'hffffffff;
      default: fw_rom_word = 32'h0000_0000;
    endcase
  end
endfunction
