// Auto-generated by scripts/gen_firmware_hex.py - do not edit.
localparam FW_WORDS = 16;
function [31:0] fw_rom_word;
  input [31:0] idx;
  begin
    case (idx)
      0: fw_rom_word = 32'hc01fafff;
      1: fw_rom_word = 32'hc000b010;
      2: fw_rom_word = 32'ha2b6a800;
      3: fw_rom_word = 32'hc2a2b800;
      4: fw_rom_word = 32'hc0005048;
      5: fw_rom_word = 32'h0aea0800;
      6: fw_rom_word = 32'hc0005069;
      7: fw_rom_word = 32'h0aea0800;
      8: fw_rom_word = 32'hc0005021;
      9: fw_rom_word = 32'h0aea0800;
      10: fw_rom_word = 32'hc000500d;
      11: fw_rom_word = 32'h0aea0800;
      12: fw_rom_word = 32'hc000500a;
      13: fw_rom_word = 32'h0aea0800;
      14: fw_rom_word = 32'h00000000;
      15: fw_rom_word = 32'h43e007fc;
      default: fw_rom_word = 32'h0000_0000;
    endcase
  end
endfunction
