//=====-- E32CSubtarget.h - Define Subtarget for the E32C -----*- C++ -*--==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares the E32C specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_E32C_E32CSUBTARGET_H
#define LLVM_LIB_TARGET_E32C_E32CSUBTARGET_H

#include "E32CFrameLowering.h"
#include "E32CISelLowering.h"
#include "E32CInstrInfo.h"
#include "E32CSelectionDAGInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Target/TargetMachine.h"

#define GET_SUBTARGETINFO_HEADER
#include "E32CGenSubtargetInfo.inc"

namespace llvm {

class E32CSubtarget : public E32CGenSubtargetInfo {
public:
  // This constructor initializes the data members to match that
  // of the specified triple.
  E32CSubtarget(const Triple &TargetTriple, StringRef Cpu,
                 StringRef FeatureString, const TargetMachine &TM,
                 const TargetOptions &Options, CodeModel::Model CodeModel,
                 CodeGenOptLevel OptLevel);

  // ParseSubtargetFeatures - Parses features string setting specified
  // subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);

  E32CSubtarget &initializeSubtargetDependencies(StringRef CPU, StringRef FS);

  void initSubtargetFeatures(StringRef CPU, StringRef FS);

  bool enableMachineScheduler() const override { return true; }

  const E32CInstrInfo *getInstrInfo() const override { return &InstrInfo; }

  const TargetFrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }

  const E32CRegisterInfo *getRegisterInfo() const override {
    return &InstrInfo.getRegisterInfo();
  }

  const E32CTargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }

  const E32CSelectionDAGInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }

private:
  E32CFrameLowering FrameLowering;
  E32CInstrInfo InstrInfo;
  E32CTargetLowering TLInfo;
  E32CSelectionDAGInfo TSInfo;
};
} // namespace llvm

#endif // LLVM_LIB_TARGET_E32C_E32CSUBTARGET_H
