#!/usr/bin/env python3
"""Generate PSRAM byte-bank hex files for FPGA init (from .asm source)."""

from __future__ import annotations

import argparse
import os
import re
import time
from pathlib import Path

from core.asm import assemble_text

ROOT = Path(__file__).resolve().parents[1]

_OP_ADDI = 0b110000
_OP_JMP = 0b010000
_OP_WRITESPR = 0b011001
_EXPECTED_VECTOR = 0x100


def _imm16_sext(w: int) -> int:
    imm11 = w & 0x7FF
    immh = (w >> 16) & 0x1F
    imm16 = (immh << 11) | imm11
    if imm16 & 0x8000:
        imm16 -= 1 << 16
    return imm16


def _pack_addi0_rd_imm(rd: int, imm16: int) -> int:
    imm16 &= 0xFFFF
    immh = (imm16 >> 11) & 0x1F
    imm11 = imm16 & 0x7FF
    return (_OP_ADDI << 26) | (immh << 16) | (rd << 11) | imm11


def _find_irq_vector_from_asm(source: str) -> int | None:
    m = re.search(
        r"WRITESPR\s+\d+\s+1\s*$",
        source,
        re.MULTILINE,
    )
    if not m:
        return None
    for line in source.splitlines():
        if "WRITESPR" in line and line.strip().endswith("1"):
            parts = line.split()
            if len(parts) >= 3 and parts[0].upper() == "WRITESPR" and parts[2] == "1":
                prev = None
                for pl in source.splitlines():
                    if pl.strip().startswith("ADDI") and "21" in pl.split():
                        toks = pl.split()
                        if len(toks) >= 4:
                            try:
                                prev = int(toks[3], 0)
                            except ValueError:
                                pass
                return prev
    return None


def _find_irq_vector_from_words(words: list[int]) -> int | None:
    for i, w in enumerate(words):
        if (w >> 26) != _OP_WRITESPR:
            continue
        spr = (w >> 11) & 0x1F
        if spr != 1:
            continue
        if i == 0:
            return None
        prev = words[i - 1]
        if (prev >> 26) != _OP_ADDI:
            return None
        if ((prev >> 21) & 0x1F) != 0:
            return None
        return _imm16_sext(prev) & 0xFFFFFFFF
    return None


def patch_idle_jmp_loop(words: list[int]) -> None:
    """Optional: MOV r15,0 … idle … JMP r15,0 — patch MOV to idle entry byte address."""
    for i in range(len(words)):
        jmp = words[i]
        if (jmp >> 26) != _OP_JMP or ((jmp >> 21) & 0x1F) != 15:
            continue
        for j in range(i - 1, -1, -1):
            w = words[j]
            if (w >> 26) != _OP_ADDI:
                continue
            if ((w >> 21) & 0x1F) != 0 or ((w >> 11) & 0x1F) != 15:
                continue
            idle_byte = (j + 1) * 4
            words[j] = _pack_addi0_rd_imm(15, idle_byte)
            print(f"  idle loop entry @ 0x{idle_byte:x}: patched MOV r15 (word {j})")
            return
    return


def _write_text_retry(path: Path, text: str, *, retries: int = 8) -> None:
    """Write file on Windows even if Gowin/IDE briefly locks the old copy."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    last_err: OSError | None = None
    for attempt in range(retries):
        try:
            tmp.write_text(text, encoding="ascii", newline="\n")
            os.replace(tmp, path)
            return
        except OSError as exc:
            last_err = exc
            if tmp.exists():
                try:
                    tmp.unlink()
                except OSError:
                    pass
            if attempt + 1 < retries:
                time.sleep(0.15 * (attempt + 1))
    raise SystemExit(
        f"Cannot write {path} ({last_err}). "
        "Close Gowin IDE or any tool using test/src/firmware_b*.hex, then retry."
    ) from last_err


def write_bank(path: Path, words: list[int], byte_lane: int) -> None:
    lines = [f"{(w >> (8 * byte_lane)) & 0xFF:02x}\n" for w in words]
    _write_text_retry(path, "".join(lines))


def write_instr_rom_hex(path: Path, words: list[int], rom_words: int) -> None:
    prog = list(words)
    while len(prog) < rom_words:
        prog.append(0)
    if len(prog) > rom_words:
        raise SystemExit(f"firmware {len(prog)} words exceeds IF ROM size {rom_words}")
    lines = [f"{w:08x}\n" for w in prog[:rom_words]]
    _write_text_retry(path, "".join(lines))


def write_fetch_rom_svh(path: Path, words: list[int], rom_words: int) -> None:
    prog = list(words)
    while prog and prog[-1] == 0:
        prog.pop()
    while len(prog) < rom_words:
        prog.append(0)
    if len(prog) > rom_words:
        raise SystemExit(f"firmware {len(prog)} words exceeds IF ROM size {rom_words}")
    idx_w = max(1, (rom_words - 1).bit_length())
    lines = [
        "// Auto-generated by scripts/gen_firmware_hex.py - do not edit.\n",
    ]
    for i, w in enumerate(prog[:rom_words]):
        lines.append(f"            {idx_w}'d{i}: forced_instr = 32'h{w:08x};\n")
    lines.append("            default: forced_instr = 32'h0000_0000;\n")
    _write_text_retry(path, "".join(lines))


def write_rom_svh(path: Path, words: list[int]) -> None:
    prog = list(words)
    while prog and prog[-1] == 0:
        prog.pop()
    if not prog:
        prog = [0]
    n = len(prog)
    lines = [
        "// Auto-generated by scripts/gen_firmware_hex.py - do not edit.\n",
        f"localparam FW_WORDS = {n};\n",
        "function [31:0] fw_rom_word;\n",
        "  input [31:0] idx;\n",
        "  begin\n",
        "    case (idx)\n",
    ]
    for i, w in enumerate(prog):
        lines.append(f"      {i}: fw_rom_word = 32'h{w:08x};\n")
    lines.append("      default: fw_rom_word = 32'h0000_0000;\n")
    lines.append("    endcase\n")
    lines.append("  end\n")
    lines.append("endfunction\n")
    _write_text_retry(path, "".join(lines))


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--asm", type=Path, default=ROOT / "examples" / "blink_uart.asm")
    p.add_argument("--words", type=int, default=1024, help="Pad image length (data / hex banks)")
    p.add_argument(
        "--if-rom-words",
        type=int,
        default=512,
        help="Instruction ROM depth for fetch_rom_nop.svh and instr_rom.hex (TN9K BRAM)",
    )
    p.add_argument("--out-dir", type=Path, default=ROOT / "test" / "src")
    p.add_argument("--handler", type=Path, default=None)
    p.add_argument(
        "--handler-addr",
        type=lambda s: int(s, 0),
        default=0x100,
        help="Byte address for IRQ handler (default 0x100)",
    )
    p.add_argument(
        "--skip-fetch-rom",
        action="store_true",
        help="Do not write fetch_rom_nop.svh (TN9K boot-RAM path)",
    )
    p.add_argument(
        "--emit-store-hex",
        action="store_true",
        help="Write firmware_store_b*.hex for program store @ 0x0100_0000",
    )
    args = p.parse_args()

    source = args.asm.read_text(encoding="utf-8")
    words = assemble_text(source)
    patch_idle_jmp_loop(words)

    vector = _find_irq_vector_from_words(words)
    if vector is not None and vector != args.handler_addr:
        raise SystemExit(
            f"IRQ vector in asm (0x{vector:x}) != --handler-addr (0x{args.handler_addr:x})"
        )

    if args.handler is not None:
        handler_words = assemble_text(args.handler.read_text(encoding="utf-8"))
        idx = args.handler_addr // 4
        if len(words) > idx:
            raise SystemExit(
                f"main ({len(words)} words) overlaps handler @ 0x{args.handler_addr:x}"
            )
        while len(words) < idx:
            words.append(0)
        words.extend(handler_words)

    nop = 0x0000_0000
    while len(words) < args.words:
        words.append(nop)

    out = args.out_dir
    write_bank(out / "firmware_b0.hex", words, 0)
    write_bank(out / "firmware_b1.hex", words, 1)
    write_bank(out / "firmware_b2.hex", words, 2)
    write_bank(out / "firmware_b3.hex", words, 3)
    write_rom_svh(out / "firmware_rom.svh", words)
    if not args.skip_fetch_rom:
        write_fetch_rom_svh(out / "fetch_rom_nop.svh", words, args.if_rom_words)
        write_instr_rom_hex(out / "instr_rom.hex", words, args.if_rom_words)
    if args.emit_store_hex:
        write_bank(out / "firmware_store_b0.hex", words, 0)
        write_bank(out / "firmware_store_b1.hex", words, 1)
        write_bank(out / "firmware_store_b2.hex", words, 2)
        write_bank(out / "firmware_store_b3.hex", words, 3)

    print(f"Wrote {len(words)} words from {args.asm}")
    print(f"  handler @ 0x{args.handler_addr:x}, vector 0x{vector or _EXPECTED_VECTOR:x}")
    extras = "firmware_b0..b3.hex, firmware_rom.svh"
    if not args.skip_fetch_rom:
        extras += ", fetch_rom_nop.svh, instr_rom.hex"
    if args.emit_store_hex:
        extras += ", firmware_store_b0..b3.hex"
    print(f"  -> {out}/{extras}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
