#!/usr/bin/env python3
"""Generate E32CInstrInfo.generated.td from docs/isa/opcodes.yaml."""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OPCODES = ROOT / "docs" / "isa" / "opcodes.yaml"
OUT = ROOT / "toolchain" / "llvm" / "E32C" / "E32CInstrInfo.generated.td"

COND_ALIAS = {
    "BEQ": 0,
    "BNE": 1,
    "BCS": 2,
    "BHS": 2,
    "BCC": 3,
    "BLO": 3,
    "BMI": 4,
    "BPL": 5,
    "BVS": 6,
    "BVC": 7,
    "BHI": 8,
    "BLS": 9,
    "BGE": 10,
    "BLT": 11,
    "BGT": 12,
    "BLE": 13,
    "BAL": 14,
}


def _opc_bits(s: str | int) -> str:
    if isinstance(s, int):
        return f"0b{s:06b}"
    s = str(s).strip()
    if s.startswith("0b"):
        return f"0b{s[2:]}"
    return s


def _asm_rrr(mn: str, fields: list[str]) -> str:
    ops = " ".join(f"${f}" for f in fields)
    return f"{mn} {ops}"


def _emit_rrr(mn: str, opc: str, fields: list[dict]) -> str:
    fmap = {f["name"]: f for f in fields}
    order = ["r1", "r2", "res"]
    asm = _asm_rrr(mn, [n for n in order if n in fmap])
    return f"""def {mn} : E32CRrr<{_opc_bits(opc)}> {{
  let AsmString = "{asm}";
  let Pattern = [];
}}
"""


def _emit_load_store(mn: str, opc: str, fields: list[dict]) -> str:
    return f"""def {mn} : E32CLoadStore<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $raddr $rdest $mask $imm11";
  let Pattern = [];
}}
"""


def _emit_store(mn: str, opc: str, fields: list[dict]) -> str:
    return f"""def {mn} : E32CStore<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $raddr $rdata $mask $imm11";
  let Pattern = [];
}}
"""


def _emit_branch(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CBranch<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $raddr $imm11";
  let Pattern = [];
}}
"""


def _emit_branch_cond(mn: str, opc: str, cond: int | None = None) -> str:
    if cond is not None:
        return f"""def {mn} : E32CBranchCond<{_opc_bits(opc)}, {cond}> {{
  let AsmString = "{mn} $raddr $imm11";
  let Pattern = [];
}}
"""
    return f"""def {mn} : E32CBranchCondVar<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $raddr $imm11";
  let Pattern = [];
}}
"""


def _emit_imm16(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CImm16<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $r1 $res $imm16";
  let Pattern = [];
}}
"""


def _emit_mul(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CMul<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $r1 $r2 $res $resh";
  let Pattern = [];
}}
"""


def _emit_mla(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CMla<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $r1 $r2 $racc $res";
  let Pattern = [];
}}
"""


def _emit_spr(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CSpr<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $r1 $spr";
  let Pattern = [];
}}
"""


def _emit_strex(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CStrex<{_opc_bits(opc)}> {{
  let AsmString = "{mn} $raddr $rsrc $rstatus $imm11";
  let Pattern = [];
}}
"""


def _emit_bare(mn: str, opc: str) -> str:
    return f"""def {mn} : E32CBare<{_opc_bits(opc)}> {{
  let AsmString = "{mn}";
  let Pattern = [];
}}
"""


def _emit_nop() -> str:
    return """def NOP : E32CNop {
  let AsmString = "NOP";
  let Pattern = [];
}
"""


def _emit_halt() -> str:
    return """def HALT : E32CHalt {
  let AsmString = "HALT";
  let Pattern = [];
}
"""


def main() -> int:
    with OPCODES.open(encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    lines = [
        "// Auto-generated by scripts/gen_llvm_e32c_td.py — do not edit.",
        "",
    ]
    seen: set[str] = set()
    bj_opc = None

    for ent in doc["instructions"]:
        mn = str(ent["mnemonic"]).upper()
        if mn in seen:
            continue
        seen.add(mn)
        fmt = str(ent["format"])
        opc = ent["opcode"]
        fields = ent.get("fields", [])

        if fmt in ("special_nop", "special_halt"):
            continue  # defined in E32CInstrFormats.td
        elif fmt == "rrr":
            lines.append(_emit_rrr(mn, opc, fields))
        elif fmt == "load_store":
            lines.append(_emit_load_store(mn, opc, fields))
        elif fmt == "store":
            lines.append(_emit_store(mn, opc, fields))
        elif fmt == "branch":
            lines.append(_emit_branch(mn, opc))
        elif fmt == "branch_cond":
            bj_opc = opc
            lines.append(_emit_branch_cond(mn, opc))
        elif fmt == "imm16":
            lines.append(_emit_imm16(mn, opc))
        elif fmt == "mul":
            lines.append(_emit_mul(mn, opc))
        elif fmt == "mla":
            lines.append(_emit_mla(mn, opc))
        elif fmt == "spr":
            lines.append(_emit_spr(mn, opc))
        elif fmt == "strex":
            lines.append(_emit_strex(mn, opc))
        elif fmt == "bare":
            lines.append(_emit_bare(mn, opc))
        else:
            print(f"skip unknown format {fmt} for {mn}", file=sys.stderr)
        lines.append("")

    if bj_opc is not None:
        for alias, cond in COND_ALIAS.items():
            if alias in seen:
                continue
            seen.add(alias)
            lines.append(_emit_branch_cond(alias, bj_opc, cond))
            lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(seen)} mnemonics)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
